# Generated by Django 2.2.10 on 2021-03-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type_answer', models.CharField(choices=[('text', 'Ответ текстом'), ('single', 'Один вариант'), ('multi', 'Несколько вариантов')], default='text', max_length=16)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='interview.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='question.Question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
